### ISSUE TITLE
Баг с алгебраическими формулами

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/MathGame#44]
При применении к выражению: **2-(1-a)**
Правила: **a+(b+c) ~> a+b+c**
Случается неожиданное падение :(

**Comment by vikto9494** [comment]
Посмотрел, у меня не воспроизводится. В конкретно таком примере у меня такое правило сейчас вообще не показывается как применимое (и это правильно, поскольку в выражении перед скобками есть дополнительный минус, который не матчится в правиле)

Сделаю игру на полиномы, считая что минус поддерживается; там посмотрим, будет ли это падать.
